### ISSUE TITLE
Redirect to the app

### ISSUE THREAD

**Issue by nauj27** [rycus86/TweetWear#36]
![Screenshot_20190530-195702](https://user-images.githubusercontent.com/2448/58653393-e4f00d80-8315-11e9-91ad-5a73b6447fd1.jpg)

With the last update, the login and authorization site opens, but it stalls in redirecting to the app...

**Comment by rycus86** [comment]
Eh, thanks for reporting! Couldn't test it in a real device...
Will try to fix the redirect later.

**Comment by nauj27** [comment]
Don't you have a real device with Android? I think that you can try in the emulator of Android Studio 😉

**Comment by rycus86** [comment]
OK, I tested it in an emulator, had one extra place I had to fix up the authorization flow. I've released a new `0.4.7` version to the Play Store, hopefully this will fix it. :)
Thanks!
