### ISSUE TITLE
Only "New Tweet" on Wear device

### ISSUE THREAD

**Issue by nauj27** [rycus86/TweetWear#37]
Everything related with login and authorization seems to work fine with the current version, but in the watch I only can found "New Tweet" app.

How can I see the Timeline? I have a Ticwatch Pro with Android Wear 2.6.

**Comment by rycus86** [comment]
Glad to hear!
You'll see the latest Tweets from your timeline as notifications, there isn't an app to see previous tweets on the watch.

**Comment by nauj27** [comment]
Well, then it'working fine now!
