### ISSUE TITLE
İstanbul gay aktif 

### ISSUE THREAD

**Issue by Istanbulgay** [rycus86/TweetWear#38]
Meehaba21 175 70  bahcelievler ful aktif masörüm yer var 19 cm kalın 0552 266 47 82 #bahcelievlergay #istanbul #bakırköy #şirinevler #taksim #gay #aktif #pasif #travesti #beylikdüzüeskort
![IMG-20190523-WA0047](https://user-images.githubusercontent.com/51692637/59247402-eaa7f600-8c27-11e9-9934-f520179f87f5.jpg)

**Comment by rycus86** [comment]
This doesn't seem relevant...?
